language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

services:
    - riak

install:
    - sudo sed -i -e "s/search = off/search = on/g" /etc/riak/riak.conf
    - sudo sed -i -e "s/storage_backend = .*/storage_backend = memory/g" /etc/riak/riak.conf
    - sudo service riak restart
    - sudo make create-data-types
    - composer self-update
    - composer --prefer-source install

script:
    - make phpcs phpunit-coverage-clover

after_script:
    - ./vendor/bin/coveralls -v